### ISSUE TITLE
Possible issue with _check_difficulty_buttons in exercise 14.4 solution

### ISSUE THREAD

**Issue by kevinbowen777** [ehmatthes/pcc_2e_ai_solutions#1]
Looking at the method `_check_difficulty_buttons`, in the solution to exercise 14.4, the if/elif conditions check never actually start the game. Shouldn't the structure of the checks look like the following?:
``` 
       if easy_button_clicked:
            self.settings.difficulty_level = 'easy'
            self._start_game()
        elif medium_button_clicked:
            self.settings.difficulty_level = 'medium'
            self._start_game()
        elif diff_button_clicked:
            self.settings.difficulty_level = 'difficult'
            self._start_game()
```
Otherwise, the game never actually starts. Is there a cleaner way to pass the settings.difficulty_level here, or is this reasonable? Thanks.

**Comment by ehmatthes** [comment]
Hi, sorry to take so long to get to this. I saw it when you first posted, and then lost track of it.

You are correct in that pressing the buttons should give some indication that the difficulty level has been selected. One good way to do that would be to have a different color for the current difficulty level, and change the color of the button when you click a different level.

The buttons do work; if you press a particular button and then press the play button, you play the game at the selected difficulty level.

When I have a chance, I'll come back to this and make a visual indication of which level has been selected. I like your solution as well. If you're going with your approach, I would suggest removing the play button entirely and just having the three level buttons.

Thank you for bringing this up. :)
